image: go1.3
env:
  - GOROOT=/usr/local/go
  - PATH=$PATH:$GOROOT/bin:$GOPATH/bin

script:
  - go get github.com/spf13/hugo
  - hugo -t drone

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: blog.drone.io
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: public/
    target: /
    recursive: true
    when:
      owner: drone